/*
 * Wikipedia API
 *
 * This is an api that searches a wikipage
 *
 * API version: 1.0.1
 * Contact: bchristian14@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Website struct {

	ImageSRCs *[]ImageSrCsInner `json:"ImageSRCs,omitempty"`

	WebsiteLinks *[]WebsiteLinksInner `json:"WebsiteLinks,omitempty"`

	WebsitePages *[]WebsitePagesInner `json:"WebsitePages,omitempty"`

	WebsiteData *[]WebsiteDataInner `json:"WebsiteData,omitempty"`
}
