/*
 * Wikipedia API
 *
 * This is an api that searches a wikipage
 *
 * API version: 1.0.0
 * Contact: bchristian14@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/VoithAPI/WikipediaAPI/1.0.0/",
		Index,
	},

	Route{
		"WikipagesUrlGet",
		strings.ToUpper("Get"),
		"/VoithAPI/WikipediaAPI/1.0.0/wikipages/{url}",
		WikipagesUrlGet,
	},

	Route{
		"WikipagesUrlImageSRCsGet",
		strings.ToUpper("Get"),
		"/VoithAPI/WikipediaAPI/1.0.0/wikipages/{url}/ImageSRCs",
		WikipagesUrlImageSRCsGet,
	},

	Route{
		"WikipagesUrlWebsiteDataGet",
		strings.ToUpper("Get"),
		"/VoithAPI/WikipediaAPI/1.0.0/wikipages/{url}/WebsiteData",
		WikipagesUrlWebsiteDataGet,
	},

	Route{
		"WikipagesUrlWebsiteLinksGet",
		strings.ToUpper("Get"),
		"/VoithAPI/WikipediaAPI/1.0.0/wikipages/{url}/WebsiteLinks",
		WikipagesUrlWebsiteLinksGet,
	},

	Route{
		"WikipagesUrlWebsitePagesGet",
		strings.ToUpper("Get"),
		"/VoithAPI/WikipediaAPI/1.0.0/wikipages/{url}/WebsitePages",
		WikipagesUrlWebsitePagesGet,
	},
}
